name: Boilerplate CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check Style
        run: mvn git-code-format:format-code
      - name: Tests
        run: mvn test
