name: FeatureCI
on:
  push:
    branches:
      - '*'
  pull-request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check Style
        run: mvn git-code-format:format-code -DglobPattern=**/*
      - name: Tests
        run: mvn test
